services:
  backend:
    image: ghcr.io/heinischvalentin/upstate-backend:latest
    restart: unless-stopped
    volumes:
      - ./conf.yml:/config/config.yaml:ro
    env_file:
      - .env

  frontend:
    image: ghcr.io/heinischvalentin/upstate-frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend
